# Generated by Django 5.0 on 2023-12-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_part', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
