# Generated by Django 5.0 on 2023-12-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_text_comment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='text',
        ),
    ]
